import type { Metadata } from "next";
import { ReactNode } from "react";

import { Providers } from "./providers";

import "./globals.css";

import { Footer, Header } from "#/components";

export const metadata: Metadata = {
  title: "Google AI Hackathon",
  description: "Generated by Enigma Team.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          <>{children}</>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
